/* /patch_notes [count] [channel] - admin-only: announce the most recent
 * changes to the realm, in the Herald's voice, citing real commit subjects
 * from UPDATELOG.md rather than requiring anyone to hand-write announcement
 * text.
 *
 * UPDATELOG.md (generated by `npm run updatelog` — see scripts/updatelog.js)
 * ships inside the bot's own Docker image, unlike .git, which .dockerignore
 * excludes. That makes it the only changelog data available to the running
 * bot in production — this command can't shell out to `git log` itself.
 * Regenerate and commit UPDATELOG.md before a change should be citable here.
 *
 * adminOnly + hidden mirror the other admin utility commands (see
 * commands/prompts/point_adjust.js): Discord restricts it to members with
 * the Manage Server permission, and it's kept out of the generated /help.
 */

const fs = require('fs');
const path = require('path');
const { ApplicationCommandOptionType, ChannelType, EmbedBuilder } = require('discord.js');
const { findAnnounceChannel } = require('../../src/findAnnounceChannel');
const flavor = require('../../flavor_text');

const EMBED_COLOR = 0xd4af37; // heraldic gold
const DEFAULT_COUNT = 5;
const MAX_COUNT = 15;
const UPDATELOG_PATH = path.join(__dirname, '..', '..', 'UPDATELOG.md');

// Pure repo bookkeeping, never worth announcing to players.
const SKIP_SUBJECTS = new Set(['Regenerate UPDATELOG.md']);

// Matches one generated bullet line, e.g. "- Fixed the thing (`abc1234`)".
// See scripts/updatelog.js for the format this parses.
const COMMIT_LINE = /^- (.+?) \(`[0-9a-f]+`\)$/gm;

const pick = (lines) => lines[Math.floor(Math.random() * lines.length)];

// Newest-first commit subjects from UPDATELOG.md, skipping date headers and
// pure-bookkeeping commits. Returns null if the file couldn't be read.
const readRecentChanges = () => {
    let content;
    try {
        content = fs.readFileSync(UPDATELOG_PATH, 'utf8');
    } catch (error) {
        console.error('patch_notes: could not read UPDATELOG.md:', error.message);
        return null;
    }

    const subjects = [];
    for (const match of content.matchAll(COMMIT_LINE)) {
        const subject = match[1].trim();
        if (!SKIP_SUBJECTS.has(subject)) subjects.push(subject);
    }
    return subjects;
};

// Discord caps embed descriptions at 4096 characters; drop trailing entries
// until it fits, noting how many were cut (mirrors weeklyRecap.js's
// fitFieldLines, just against the description limit instead of a field's).
const DESCRIPTION_MAX = 4096;
const fitLines = (lines) => {
    for (let kept = lines.length; kept > 0; kept--) {
        const omitted = lines.length - kept;
        const suffix = omitted ? `\n...and ${omitted} more` : '';
        const text = lines.slice(0, kept).join('\n') + suffix;
        if (text.length <= DESCRIPTION_MAX) return text;
    }
    return lines[0].slice(0, DESCRIPTION_MAX);
};

const patchNotes = async function (interaction) {
    const guild = interaction.guild;
    const admin = interaction.member;
    const count = interaction.options.getInteger('count') || DEFAULT_COUNT;
    const requestedChannel = interaction.options.getChannel('channel');

    const channel = requestedChannel || findAnnounceChannel(guild);
    if (!channel) {
        await interaction.editReply('Alack! I find no chamber in which to post that decree, Milord.');
        return;
    }

    const subjects = readRecentChanges();
    if (subjects === null) {
        await interaction.editReply("Alack! The royal scribes' ledger could not be read, Milord.");
        return;
    }
    if (subjects.length === 0) {
        await interaction.editReply('The royal scribes report no decrees worth announcing at this time, Milord.');
        return;
    }

    const cited = subjects.slice(0, count);
    const description = `${pick(flavor.patchNotesIntroLines())}\n\n${fitLines(cited.map((s) => `• ${s}`))}`;

    const embed = new EmbedBuilder()
        .setColor(EMBED_COLOR)
        .setTitle('By Royal Decree: Recent Improvements to the Realm')
        .setDescription(description)
        .setFooter({ text: `Proclaimed by ${admin.displayName}` })
        .setTimestamp();

    try {
        await channel.send({ embeds: [embed] });
    } catch (error) {
        console.error('patch_notes: failed to post announcement:', error);
        await interaction.editReply(`Alack! I could not deliver that decree to #${channel.name}, Milord.`);
        return;
    }

    console.log(`Patch notes (guild ${guild.id}): ${admin.displayName} (${admin.id}) cited ${cited.length} recent change(s) in #${channel.name}.`);
    await interaction.editReply(`By royal decree, thy proclamation has been posted in #${channel.name}.`);
};

module.exports = {
    description: "Announce the most recent changes to the realm, in the Herald's voice",
    category: 'UTILITY',
    hidden: true, // out of the generated /help
    adminOnly: true, // registered with Discord, but only members with Manage Server can see/run it
    options: [
        {
            name: 'count',
            description: `How many recent changes to cite (default ${DEFAULT_COUNT}, max ${MAX_COUNT})`,
            type: ApplicationCommandOptionType.Integer,
            required: false,
            minValue: 1,
            maxValue: MAX_COUNT,
        },
        {
            name: 'channel',
            description: "Where to post (default: the guild's announce channel)",
            type: ApplicationCommandOptionType.Channel,
            channelTypes: [ChannelType.GuildText],
            required: false,
        },
    ],
    run: patchNotes,
};
