/* The Herald's shop catalog: every item, title, class and race that can appear
 * in the daily shop (see commands/passive/shop.js). Written by hand from fan
 * knowledge of WoW, RuneScape, Guild Wars and Final Fantasy. The names are
 * for flavor only, not real drop tables or game data.
 *
 * Prices follow the house rule:
 *   10 - the usual item
 *   25 - lore-significant or extremely recognizable to its fanbase
 *   50 - legendary
 *
 * `slot` is set on gear only (helm, chest, pants, weapon, gloves, cape, boots).
 * `id` is the stable key stored in DynamoDB; never change an id once it has
 * shipped, or owned items stop matching their catalog entry.
 *
 * Exposes:
 *   GEAR_SLOTS - the seven equipment slots, in display order
 *   GEAR, TITLES, CLASSES, RACES - arrays of catalog entries
 *   DEFAULT_CLASS - the class everyone starts as
 *   findEntry(id) - the catalog entry for an id, or null
 */

const GEAR_SLOTS = ['helm', 'chest', 'pants', 'weapon', 'gloves', 'cape', 'boots'];

const DEFAULT_CLASS = { id: 'peasant', name: 'Peasant', price: 0 };

const GEAR = [
    // Helm
    { id: 'birthright', name: 'Birthright', slot: 'helm', price: 40, franchise: 'Baldur\'s Gate' },
    { id: 'black_knight_helm', name: 'Black Knight Helm', slot: 'helm', price: 35, franchise: 'Dark Souls' },
    { id: 'catarina_helm', name: 'Catarina Helm', slot: 'helm', price: 25, franchise: 'Dark Souls' },
    { id: 'malenias_winged_helm', name: 'Malenia\'s Winged Helm', slot: 'helm', price: 50, franchise: 'Elden Ring' },
    { id: 'circlet', name: 'Circlet', slot: 'helm', price: 15, franchise: 'Final Fantasy' },
    { id: 'diamond_helm', name: 'Diamond Helm', slot: 'helm', price: 20, franchise: 'Final Fantasy' },
    { id: 'flame_helm', name: 'Flame Helm', slot: 'helm', price: 15, franchise: 'Final Fantasy' },
    { id: 'genji_helm', name: 'Genji Helm', slot: 'helm', price: 25, franchise: 'Final Fantasy' },
    { id: 'genji_helmet', name: 'Genji Helmet', slot: 'helm', price: 10, franchise: 'Final Fantasy' },
    { id: 'gold_helm', name: 'Gold Helm', slot: 'helm', price: 10, franchise: 'Final Fantasy' },
    { id: 'ice_helm', name: 'Ice Helm', slot: 'helm', price: 15, franchise: 'Final Fantasy' },
    { id: 'mythril_helm', name: 'Mythril Helm', slot: 'helm', price: 10, franchise: 'Final Fantasy' },
    { id: 'onion_helm', name: 'Onion Helm', slot: 'helm', price: 30, franchise: 'Final Fantasy' },
    { id: 'ribbon', name: 'Ribbon', slot: 'helm', price: 20, franchise: 'Final Fantasy' },
    { id: 'ultima_helm', name: 'Ultima Helm', slot: 'helm', price: 40, franchise: 'Final Fantasy' },
    { id: 'assassin_mask', name: 'Assassin Mask', slot: 'helm', price: 10, franchise: 'Guild Wars' },
    { id: 'destroyer_helm', name: 'Destroyer Helm', slot: 'helm', price: 35, franchise: 'Guild Wars' },
    { id: 'gladiator_helm', name: 'Gladiator Helm', slot: 'helm', price: 10, franchise: 'Guild Wars' },
    { id: 'monk_halo', name: 'Monk Halo', slot: 'helm', price: 10, franchise: 'Guild Wars' },
    { id: 'necromancer_circlet', name: 'Necromancer Circlet', slot: 'helm', price: 10, franchise: 'Guild Wars' },
    { id: 'obsidian_helm', name: 'Obsidian Helm', slot: 'helm', price: 25, franchise: 'Guild Wars' },
    { id: 'ranger_mask', name: 'Ranger Mask', slot: 'helm', price: 10, franchise: 'Guild Wars' },
    { id: 'diadem_of_ravenclaw', name: 'Diadem of Ravenclaw', slot: 'helm', price: 50, franchise: 'Harry Potter' },
    { id: 'sorting_hat', name: 'Sorting Hat', slot: 'helm', price: 25, franchise: 'Harry Potter' },
    { id: 'gondorian_helm', name: 'Gondorian Helm', slot: 'helm', price: 15, franchise: 'Lord of the Rings' },
    { id: 'winged_crown_of_gondor', name: 'Winged Crown of Gondor', slot: 'helm', price: 40, franchise: 'Lord of the Rings' },
    { id: 'diamond_helmet', name: 'Diamond Helmet', slot: 'helm', price: 20, franchise: 'Minecraft' },
    { id: 'iron_helmet', name: 'Iron Helmet', slot: 'helm', price: 10, franchise: 'Minecraft' },
    { id: 'netherite_helmet', name: 'Netherite Helmet', slot: 'helm', price: 35, franchise: 'Minecraft' },
    { id: 'turtle_shell', name: 'Turtle Shell', slot: 'helm', price: 25, franchise: 'Minecraft' },
    { id: 'ahrims_hood', name: 'Ahrim\'s Hood', slot: 'helm', price: 20, franchise: 'RuneScape' },
    { id: 'ancestral_hat', name: 'Ancestral Hat', slot: 'helm', price: 30, franchise: 'RuneScape' },
    { id: 'archer_helm', name: 'Archer Helm', slot: 'helm', price: 10, franchise: 'RuneScape' },
    { id: 'armadyl_helmet', name: 'Armadyl Helmet', slot: 'helm', price: 20, franchise: 'RuneScape' },
    { id: 'berserker_helm', name: 'Berserker Helm', slot: 'helm', price: 15, franchise: 'RuneScape' },
    { id: 'dharoks_helm', name: 'Dharok\'s Helm', slot: 'helm', price: 20, franchise: 'RuneScape' },
    { id: 'dragon_full_helm', name: 'Dragon Full Helm', slot: 'helm', price: 10, franchise: 'RuneScape' },
    { id: 'farseer_helm', name: 'Farseer Helm', slot: 'helm', price: 10, franchise: 'RuneScape' },
    { id: 'guthans_helm', name: 'Guthan\'s Helm', slot: 'helm', price: 20, franchise: 'RuneScape' },
    { id: 'neitiznot_helm', name: 'Helm of Neitiznot', slot: 'helm', price: 15, franchise: 'RuneScape' },
    { id: 'slayer_helmet', name: 'Slayer Helmet', slot: 'helm', price: 25, franchise: 'RuneScape' },
    { id: 'torags_helm', name: 'Torag\'s Helm', slot: 'helm', price: 20, franchise: 'RuneScape' },
    { id: 'torva_full_helm', name: 'Torva Full Helm', slot: 'helm', price: 50, franchise: 'RuneScape' },
    { id: 'veracs_helm', name: 'Verac\'s Helm', slot: 'helm', price: 20, franchise: 'RuneScape' },
    { id: 'warrior_helm', name: 'Warrior Helm', slot: 'helm', price: 10, franchise: 'RuneScape' },
    { id: 'daedric_helmet', name: 'Daedric Helmet', slot: 'helm', price: 40, franchise: 'Skyrim' },
    { id: 'konahrik', name: 'Konahrik', slot: 'helm', price: 50, franchise: 'Skyrim' },
    { id: 'masque_clavicus_vile', name: 'Masque of Clavicus Vile', slot: 'helm', price: 35, franchise: 'Skyrim' },
    { id: 'nightingale_hood', name: 'Nightingale Hood', slot: 'helm', price: 25, franchise: 'Skyrim' },
    { id: 'molten_helmet', name: 'Molten Helmet', slot: 'helm', price: 20, franchise: 'Terraria' },
    { id: 'solar_flare_helmet', name: 'Solar Flare Helmet', slot: 'helm', price: 50, franchise: 'Terraria' },
    { id: 'fierce_deity_mask', name: 'Fierce Deity\'s Mask', slot: 'helm', price: 50, franchise: 'The Legend of Zelda' },
    { id: 'arcanist_crown', name: 'Arcanist Crown', slot: 'helm', price: 20, franchise: 'WoW' },
    { id: 'bloodfang_hood', name: 'Bloodfang Hood', slot: 'helm', price: 20, franchise: 'WoW' },
    { id: 'crown_destruction', name: 'Crown of Destruction', slot: 'helm', price: 20, franchise: 'WoW' },
    { id: 'crown_sunwell', name: 'Crown of the Sunwell', slot: 'helm', price: 25, franchise: 'WoW' },
    { id: 'cursed_vision', name: 'Cursed Vision of Sargeras', slot: 'helm', price: 30, franchise: 'WoW' },
    { id: 'greathelm_crusader', name: 'Greathelm of the Crusader', slot: 'helm', price: 10, franchise: 'WoW' },
    { id: 'helm_domination', name: 'Helm of Domination', slot: 'helm', price: 40, franchise: 'WoW' },
    { id: 'helm_wrath', name: 'Helm of Wrath', slot: 'helm', price: 15, franchise: 'WoW' },
    { id: 'horns_ragnaros', name: 'Horns of Ragnaros', slot: 'helm', price: 25, franchise: 'WoW' },
    { id: 'judgement_helm', name: 'Judgement Helm', slot: 'helm', price: 20, franchise: 'WoW' },
    { id: 'mimirons_head', name: 'Mimiron\'s Head', slot: 'helm', price: 35, franchise: 'WoW' },
    { id: 'nemesis_skullcap', name: 'Nemesis Skullcap', slot: 'helm', price: 20, franchise: 'WoW' },

    // Chest
    { id: 'helldusk_armour', name: 'Helldusk Armour', slot: 'chest', price: 50, franchise: 'Baldur\'s Gate' },
    { id: 'armor_of_the_sun', name: 'Armor of the Sun', slot: 'chest', price: 30, franchise: 'Dark Souls' },
    { id: 'elite_knight_armor', name: 'Elite Knight Armor', slot: 'chest', price: 25, franchise: 'Dark Souls' },
    { id: 'havels_armor', name: 'Havel\'s Armor', slot: 'chest', price: 50, franchise: 'Dark Souls' },
    { id: 'black_knife_armor', name: 'Black Knife Armor', slot: 'chest', price: 35, franchise: 'Elden Ring' },
    { id: 'radahns_lion_armor', name: 'Radahn\'s Lion Armor', slot: 'chest', price: 50, franchise: 'Elden Ring' },
    { id: 'adamant_armor', name: 'Adamant Armor', slot: 'chest', price: 35, franchise: 'Final Fantasy' },
    { id: 'black_robe', name: 'Black Robe', slot: 'chest', price: 10, franchise: 'Final Fantasy' },
    { id: 'brave_suit', name: 'Brave Suit', slot: 'chest', price: 30, franchise: 'Final Fantasy' },
    { id: 'diamond_armor', name: 'Diamond Armor', slot: 'chest', price: 20, franchise: 'Final Fantasy' },
    { id: 'flame_mail', name: 'Flame Mail', slot: 'chest', price: 15, franchise: 'Final Fantasy' },
    { id: 'genji_armor', name: 'Genji Armor', slot: 'chest', price: 25, franchise: 'Final Fantasy' },
    { id: 'gold_armor', name: 'Gold Armor', slot: 'chest', price: 10, franchise: 'Final Fantasy' },
    { id: 'ice_armor', name: 'Ice Armor', slot: 'chest', price: 15, franchise: 'Final Fantasy' },
    { id: 'mythril_armor', name: 'Mythril Armor', slot: 'chest', price: 10, franchise: 'Final Fantasy' },
    { id: 'onyx_armor', name: 'Onyx Armor', slot: 'chest', price: 30, franchise: 'Final Fantasy' },
    { id: 'white_robe', name: 'White Robe', slot: 'chest', price: 10, franchise: 'Final Fantasy' },
    { id: 'assassin_armor', name: 'Assassin Armor', slot: 'chest', price: 15, franchise: 'Guild Wars' },
    { id: 'asura_armor', name: 'Asura Armor', slot: 'chest', price: 20, franchise: 'Guild Wars' },
    { id: 'destroyer_armor', name: 'Destroyer Armor', slot: 'chest', price: 35, franchise: 'Guild Wars' },
    { id: 'ranger_drakescale', name: 'Drakescale Armor', slot: 'chest', price: 15, franchise: 'Guild Wars' },
    { id: 'gladiator_armor', name: 'Gladiator Armor', slot: 'chest', price: 10, franchise: 'Guild Wars' },
    { id: 'monk_armor', name: 'Monk Armor', slot: 'chest', price: 15, franchise: 'Guild Wars' },
    { id: 'necromancer_armor', name: 'Necromancer Armor', slot: 'chest', price: 15, franchise: 'Guild Wars' },
    { id: 'obsidian_armor', name: 'Obsidian Armor', slot: 'chest', price: 40, franchise: 'Guild Wars' },
    { id: 'hogwarts_robes', name: 'Hogwarts Robes', slot: 'chest', price: 10, franchise: 'Harry Potter' },
    { id: 'quidditch_robes', name: 'Quidditch Robes', slot: 'chest', price: 15, franchise: 'Harry Potter' },
    { id: 'mithril_coat', name: 'Mithril Coat', slot: 'chest', price: 35, franchise: 'Lord of the Rings' },
    { id: 'rohirrim_mail', name: 'Rohirrim Mail', slot: 'chest', price: 15, franchise: 'Lord of the Rings' },
    { id: 'diamond_chestplate', name: 'Diamond Chestplate', slot: 'chest', price: 20, franchise: 'Minecraft' },
    { id: 'elytra', name: 'Elytra', slot: 'chest', price: 40, franchise: 'Minecraft' },
    { id: 'leather_tunic', name: 'Leather Tunic', slot: 'chest', price: 10, franchise: 'Minecraft' },
    { id: 'netherite_chestplate', name: 'Netherite Chestplate', slot: 'chest', price: 35, franchise: 'Minecraft' },
    { id: 'ahrims_robetop', name: 'Ahrim\'s Robetop', slot: 'chest', price: 20, franchise: 'RuneScape' },
    { id: 'ancestral_robe_top', name: 'Ancestral Robe Top', slot: 'chest', price: 30, franchise: 'RuneScape' },
    { id: 'armadyl_chestplate', name: 'Armadyl Chestplate', slot: 'chest', price: 25, franchise: 'RuneScape' },
    { id: 'bandos_chestplate', name: 'Bandos Chestplate', slot: 'chest', price: 30, franchise: 'RuneScape' },
    { id: 'barrows_platebody', name: 'Barrows Platebody', slot: 'chest', price: 25, franchise: 'RuneScape' },
    { id: 'dharoks_platebody', name: 'Dharok\'s Platebody', slot: 'chest', price: 20, franchise: 'RuneScape' },
    { id: 'dragon_chainbody', name: 'Dragon Chainbody', slot: 'chest', price: 20, franchise: 'RuneScape' },
    { id: 'dragon_platebody', name: 'Dragon Platebody', slot: 'chest', price: 25, franchise: 'RuneScape' },
    { id: 'guthans_platebody', name: 'Guthan\'s Platebody', slot: 'chest', price: 20, franchise: 'RuneScape' },
    { id: 'karils_leathertop', name: 'Karil\'s Leathertop', slot: 'chest', price: 20, franchise: 'RuneScape' },
    { id: 'rune_platebody', name: 'Rune Platebody', slot: 'chest', price: 10, franchise: 'RuneScape' },
    { id: 'torags_platebody', name: 'Torag\'s Platebody', slot: 'chest', price: 20, franchise: 'RuneScape' },
    { id: 'torva_platebody', name: 'Torva Platebody', slot: 'chest', price: 50, franchise: 'RuneScape' },
    { id: 'dragonplate_armor', name: 'Dragonplate Armor', slot: 'chest', price: 40, franchise: 'Skyrim' },
    { id: 'ebony_mail', name: 'Ebony Mail', slot: 'chest', price: 50, franchise: 'Skyrim' },
    { id: 'nightingale_armor', name: 'Nightingale Armor', slot: 'chest', price: 30, franchise: 'Skyrim' },
    { id: 'beetle_shell', name: 'Beetle Shell', slot: 'chest', price: 35, franchise: 'Terraria' },
    { id: 'hallowed_plate_mail', name: 'Hallowed Plate Mail', slot: 'chest', price: 30, franchise: 'Terraria' },
    { id: 'champions_tunic', name: 'Champion\'s Tunic', slot: 'chest', price: 35, franchise: 'The Legend of Zelda' },
    { id: 'goron_tunic', name: 'Goron Tunic', slot: 'chest', price: 20, franchise: 'The Legend of Zelda' },
    { id: 'kokiri_tunic', name: 'Kokiri Tunic', slot: 'chest', price: 10, franchise: 'The Legend of Zelda' },
    { id: 'zora_tunic', name: 'Zora Tunic', slot: 'chest', price: 20, franchise: 'The Legend of Zelda' },
    { id: 'manticore_armor', name: 'Manticore Armor', slot: 'chest', price: 25, franchise: 'The Witcher' },
    { id: 'temerian_armor', name: 'Temerian Armor', slot: 'chest', price: 15, franchise: 'The Witcher' },
    { id: 'ursine_armor', name: 'Ursine Armor', slot: 'chest', price: 25, franchise: 'The Witcher' },
    { id: 'wolven_armor', name: 'Wolven Armor', slot: 'chest', price: 25, franchise: 'The Witcher' },
    { id: 'arcanist_robe', name: 'Arcanist Robes', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'valor_breastplate', name: 'Battlegear of Valor', slot: 'chest', price: 15, franchise: 'WoW' },
    { id: 'black_dragon_plate', name: 'Black Dragon Plate', slot: 'chest', price: 25, franchise: 'WoW' },
    { id: 'bloodfang_chestpiece', name: 'Bloodfang Chestpiece', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'bloodvine_vest', name: 'Bloodvine Vest', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'breastplate_justice', name: 'Breastplate of Justice', slot: 'chest', price: 10, franchise: 'WoW' },
    { id: 'thunderfury_breastplate', name: 'Breastplate of the Highlord', slot: 'chest', price: 30, franchise: 'WoW' },
    { id: 'breastplate_wrath', name: 'Breastplate of Wrath', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'devilsaur_chest', name: 'Devilsaur Breastplate', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'dragonstalker_breastplate', name: 'Dragonstalker Breastplate', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'shoulderguards_felheart', name: 'Felheart Raiment', slot: 'chest', price: 25, franchise: 'WoW' },
    { id: 'frostfire_robe', name: 'Frostfire Robe', slot: 'chest', price: 25, franchise: 'WoW' },
    { id: 'judgement_breastplate', name: 'Judgement Breastplate', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'nemesis_robe', name: 'Nemesis Robes', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'netherwind_robe', name: 'Netherwind Robes', slot: 'chest', price: 25, franchise: 'WoW' },
    { id: 'nightstalker_chestpiece', name: 'Nightstalker Chestpiece', slot: 'chest', price: 15, franchise: 'WoW' },
    { id: 'shadowcraft_tunic', name: 'Shadowcraft Tunic', slot: 'chest', price: 20, franchise: 'WoW' },
    { id: 'shadowmourne_armor', name: 'Shadowmourne Armor', slot: 'chest', price: 40, franchise: 'WoW' },

    // Pants
    { id: 'havels_leggings', name: 'Havel\'s Leggings', slot: 'pants', price: 50, franchise: 'Dark Souls' },
    { id: 'leggings_of_artorias', name: 'Leggings of Artorias', slot: 'pants', price: 40, franchise: 'Dark Souls' },
    { id: 'adamant_leggings', name: 'Adamant Leggings', slot: 'pants', price: 35, franchise: 'Final Fantasy' },
    { id: 'diamond_leggings', name: 'Diamond Leggings', slot: 'pants', price: 20, franchise: 'Final Fantasy' },
    { id: 'gold_leggings', name: 'Gold Leggings', slot: 'pants', price: 10, franchise: 'Final Fantasy' },
    { id: 'mythril_leggings', name: 'Mythril Leggings', slot: 'pants', price: 10, franchise: 'Final Fantasy' },
    { id: 'assassin_legguards', name: 'Assassin Legguards', slot: 'pants', price: 15, franchise: 'Guild Wars' },
    { id: 'gladiator_legguards', name: 'Gladiator Legguards', slot: 'pants', price: 10, franchise: 'Guild Wars' },
    { id: 'monk_legguards', name: 'Monk Legguards', slot: 'pants', price: 15, franchise: 'Guild Wars' },
    { id: 'necromancer_legguards', name: 'Necromancer Legguards', slot: 'pants', price: 15, franchise: 'Guild Wars' },
    { id: 'obsidian_legguards', name: 'Obsidian Legguards', slot: 'pants', price: 35, franchise: 'Guild Wars' },
    { id: 'ranger_legguards', name: 'Ranger Legguards', slot: 'pants', price: 15, franchise: 'Guild Wars' },
    { id: 'netherite_leggings', name: 'Netherite Leggings', slot: 'pants', price: 35, franchise: 'Minecraft' },
    { id: 'ahrims_skirt', name: 'Ahrim\'s Robeskirt', slot: 'pants', price: 20, franchise: 'RuneScape' },
    { id: 'ancestral_robe_bottom', name: 'Ancestral Robe Bottom', slot: 'pants', price: 30, franchise: 'RuneScape' },
    { id: 'armadyl_chainskirt', name: 'Armadyl Chainskirt', slot: 'pants', price: 25, franchise: 'RuneScape' },
    { id: 'bandos_tassets', name: 'Bandos Tassets', slot: 'pants', price: 30, franchise: 'RuneScape' },
    { id: 'dharoks_platelegs', name: 'Dharok\'s Platelegs', slot: 'pants', price: 20, franchise: 'RuneScape' },
    { id: 'dragon_platelegs', name: 'Dragon Platelegs', slot: 'pants', price: 10, franchise: 'RuneScape' },
    { id: 'guthans_chainskirt', name: 'Guthan\'s Chainskirt', slot: 'pants', price: 20, franchise: 'RuneScape' },
    { id: 'karils_skirt', name: 'Karil\'s Leatherskirt', slot: 'pants', price: 20, franchise: 'RuneScape' },
    { id: 'rune_platelegs', name: 'Rune Platelegs', slot: 'pants', price: 10, franchise: 'RuneScape' },
    { id: 'torags_platelegs', name: 'Torag\'s Platelegs', slot: 'pants', price: 20, franchise: 'RuneScape' },
    { id: 'torva_platelegs', name: 'Torva Platelegs', slot: 'pants', price: 50, franchise: 'RuneScape' },
    { id: 'daedric_greaves', name: 'Daedric Greaves', slot: 'pants', price: 40, franchise: 'Skyrim' },
    { id: 'vortex_leggings', name: 'Vortex Leggings', slot: 'pants', price: 50, franchise: 'Terraria' },
    { id: 'grandmaster_ursine_trousers', name: 'Grandmaster Ursine Trousers', slot: 'pants', price: 50, franchise: 'The Witcher' },
    { id: 'manticore_trousers', name: 'Manticore Trousers', slot: 'pants', price: 25, franchise: 'The Witcher' },
    { id: 'arcanist_leggings', name: 'Arcanist Leggings', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'bloodfang_pants', name: 'Bloodfang Pants', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'chromatic_leggings', name: 'Chromatic Leggings', slot: 'pants', price: 25, franchise: 'WoW' },
    { id: 'dragonstalker_legguards', name: 'Dragonstalker Legguards', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'felheart_pants', name: 'Felheart Pants', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'judgement_legplates', name: 'Judgement Legplates', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'valor_legplates', name: 'Legplates of Valor', slot: 'pants', price: 15, franchise: 'WoW' },
    { id: 'wrath_legplates', name: 'Legplates of Wrath', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'magma_plated_legguards', name: 'Magma Plated Legguards', slot: 'pants', price: 30, franchise: 'WoW' },
    { id: 'nemesis_leggings', name: 'Nemesis Leggings', slot: 'pants', price: 20, franchise: 'WoW' },
    { id: 'netherwind_pants', name: 'Netherwind Pants', slot: 'pants', price: 25, franchise: 'WoW' },
    { id: 'thassarian_legguards', name: 'Thassarian\'s Legplates', slot: 'pants', price: 30, franchise: 'WoW' },

    // Weapon
    { id: 'baldurans_giantslayer', name: 'Balduran\'s Giantslayer', slot: 'weapon', price: 45, franchise: 'Baldur\'s Gate' },
    { id: 'nyrulna', name: 'Nyrulna', slot: 'weapon', price: 45, franchise: 'Baldur\'s Gate' },
    { id: 'black_knight_sword', name: 'Black Knight Sword', slot: 'weapon', price: 30, franchise: 'Dark Souls' },
    { id: 'claymore', name: 'Claymore', slot: 'weapon', price: 25, franchise: 'Dark Souls' },
    { id: 'moonlight_greatsword', name: 'Moonlight Greatsword', slot: 'weapon', price: 40, franchise: 'Dark Souls' },
    { id: 'uchigatana', name: 'Uchigatana', slot: 'weapon', price: 20, franchise: 'Dark Souls' },
    { id: 'zweihander', name: 'Zweihander', slot: 'weapon', price: 25, franchise: 'Dark Souls' },
    { id: 'moonveil', name: 'Moonveil', slot: 'weapon', price: 40, franchise: 'Elden Ring' },
    { id: 'rivers_of_blood', name: 'Rivers of Blood', slot: 'weapon', price: 45, franchise: 'Elden Ring' },
    { id: 'sword_of_night_and_flame', name: 'Sword of Night and Flame', slot: 'weapon', price: 40, franchise: 'Elden Ring' },
    { id: 'aegis', name: 'Aegis', slot: 'weapon', price: 30, franchise: 'Final Fantasy' },
    { id: 'apocalypse', name: 'Apocalypse', slot: 'weapon', price: 30, franchise: 'Final Fantasy' },
    { id: 'blood_sword', name: 'Blood Sword', slot: 'weapon', price: 10, franchise: 'Final Fantasy' },
    { id: 'buster_sword', name: 'Buster Sword', slot: 'weapon', price: 30, franchise: 'Final Fantasy' },
    { id: 'dragon_fist', name: 'Dragon Fist', slot: 'weapon', price: 20, franchise: 'Final Fantasy' },
    { id: 'excalibur', name: 'Excalibur', slot: 'weapon', price: 25, franchise: 'Final Fantasy' },
    { id: 'fenrir', name: 'Fenrir', slot: 'weapon', price: 30, franchise: 'Final Fantasy' },
    { id: 'flametongue', name: 'Flametongue', slot: 'weapon', price: 10, franchise: 'Final Fantasy' },
    { id: 'genji_shield', name: 'Genji Shield', slot: 'weapon', price: 20, franchise: 'Final Fantasy' },
    { id: 'ice_brand', name: 'Ice Brand', slot: 'weapon', price: 10, franchise: 'Final Fantasy' },
    { id: 'judgement_staff', name: 'Judgment Staff', slot: 'weapon', price: 25, franchise: 'Final Fantasy' },
    { id: 'masamune', name: 'Masamune', slot: 'weapon', price: 25, franchise: 'Final Fantasy' },
    { id: 'mythril_sword', name: 'Mythril Sword', slot: 'weapon', price: 10, franchise: 'Final Fantasy' },
    { id: 'ragnarok', name: 'Ragnarok', slot: 'weapon', price: 35, franchise: 'Final Fantasy' },
    { id: 'rune_blade', name: 'Rune Blade', slot: 'weapon', price: 10, franchise: 'Final Fantasy' },
    { id: 'ultima_weapon', name: 'Ultima Weapon', slot: 'weapon', price: 50, franchise: 'Final Fantasy' },
    { id: 'wizard_staff', name: 'Wizard Staff', slot: 'weapon', price: 10, franchise: 'Final Fantasy' },
    { id: 'zantetsuken', name: 'Zantetsuken', slot: 'weapon', price: 35, franchise: 'Final Fantasy' },
    { id: 'armads', name: 'Armads', slot: 'weapon', price: 35, franchise: 'Fire Emblem' },
    { id: 'brave_lance', name: 'Brave Lance', slot: 'weapon', price: 25, franchise: 'Fire Emblem' },
    { id: 'falchion', name: 'Falchion', slot: 'weapon', price: 40, franchise: 'Fire Emblem' },
    { id: 'killing_edge', name: 'Killing Edge', slot: 'weapon', price: 20, franchise: 'Fire Emblem' },
    { id: 'ragnell', name: 'Ragnell', slot: 'weapon', price: 40, franchise: 'Fire Emblem' },
    { id: 'sol_katti', name: 'Sol Katti', slot: 'weapon', price: 30, franchise: 'Fire Emblem' },
    { id: 'spear_of_assal', name: 'Spear of Assal', slot: 'weapon', price: 30, franchise: 'Fire Emblem' },
    { id: 'ascalon', name: 'Ascalon', slot: 'weapon', price: 50, franchise: 'Guild Wars' },
    { id: 'crystalline_sword', name: 'Crystalline Sword', slot: 'weapon', price: 30, franchise: 'Guild Wars' },
    { id: 'dragon_sword', name: 'Dragon Sword', slot: 'weapon', price: 10, franchise: 'Guild Wars' },
    { id: 'eternal_blade', name: 'Eternal Blade', slot: 'weapon', price: 10, franchise: 'Guild Wars' },
    { id: 'fellblade', name: 'Fellblade', slot: 'weapon', price: 10, franchise: 'Guild Wars' },
    { id: 'fiery_dragon_sword', name: 'Fiery Dragon Sword', slot: 'weapon', price: 10, franchise: 'Guild Wars' },
    { id: 'shining_blade', name: 'Shining Blade', slot: 'weapon', price: 25, franchise: 'Guild Wars' },
    { id: 'storm_bow', name: 'Storm Bow', slot: 'weapon', price: 20, franchise: 'Guild Wars' },
    { id: 'elder_wand', name: 'Elder Wand', slot: 'weapon', price: 45, franchise: 'Harry Potter' },
    { id: 'holly_phoenix_wand', name: 'Holly and Phoenix Feather Wand', slot: 'weapon', price: 20, franchise: 'Harry Potter' },
    { id: 'sword_of_gryffindor', name: 'Sword of Gryffindor', slot: 'weapon', price: 35, franchise: 'Harry Potter' },
    { id: 'anduril', name: 'Andúril', slot: 'weapon', price: 45, franchise: 'Lord of the Rings' },
    { id: 'bow_of_the_galadhrim', name: 'Bow of the Galadhrim', slot: 'weapon', price: 25, franchise: 'Lord of the Rings' },
    { id: 'glamdring', name: 'Glamdring', slot: 'weapon', price: 35, franchise: 'Lord of the Rings' },
    { id: 'orcrist', name: 'Orcrist', slot: 'weapon', price: 35, franchise: 'Lord of the Rings' },
    { id: 'sting', name: 'Sting', slot: 'weapon', price: 35, franchise: 'Lord of the Rings' },
    { id: 'diamond_sword', name: 'Diamond Sword', slot: 'weapon', price: 20, franchise: 'Minecraft' },
    { id: 'iron_sword', name: 'Iron Sword', slot: 'weapon', price: 10, franchise: 'Minecraft' },
    { id: 'netherite_sword', name: 'Netherite Sword', slot: 'weapon', price: 30, franchise: 'Minecraft' },
    { id: 'trident', name: 'Trident', slot: 'weapon', price: 30, franchise: 'Minecraft' },
    { id: 'black_hole_wand', name: 'Black Hole Wand', slot: 'weapon', price: 35, franchise: 'Noita' },
    { id: 'sparkbolt_wand', name: 'Sparkbolt Wand', slot: 'weapon', price: 10, franchise: 'Noita' },
    { id: 'wand_of_destruction', name: 'Wand of Destruction', slot: 'weapon', price: 30, franchise: 'Noita' },
    { id: 'wand_of_swiftness', name: 'Wand of Swiftness', slot: 'weapon', price: 25, franchise: 'Noita' },
    { id: 'abyssal_whip', name: 'Abyssal Whip', slot: 'weapon', price: 25, franchise: 'RuneScape' },
    { id: 'ancient_staff', name: 'Ancient Staff', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'arcane_spirit_shield', name: 'Arcane spirit shield', slot: 'weapon', price: 30, franchise: 'RuneScape' },
    { id: 'armadyl_godsword', name: 'Armadyl Godsword', slot: 'weapon', price: 35, short: 'AGS', franchise: 'RuneScape' },
    { id: 'blessed_spirit_shield', name: 'Blessed spirit shield', slot: 'weapon', price: 30, franchise: 'RuneScape' },
    { id: 'dark_bow', name: 'Dark Bow', slot: 'weapon', price: 20, franchise: 'RuneScape' },
    { id: 'dragon_claws', name: 'Dragon Claws', slot: 'weapon', price: 30, franchise: 'RuneScape' },
    { id: 'dragon_dagger', name: 'Dragon Dagger', slot: 'weapon', price: 10, short: 'DDS', franchise: 'RuneScape' },
    { id: 'dragon_scimitar', name: 'Dragon Scimitar', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'dragonfire_shield', name: 'Dragonfire Shield', slot: 'weapon', price: 30, franchise: 'RuneScape' },
    { id: 'dragonfire_ward', name: 'Dragonfire ward', slot: 'weapon', price: 25, franchise: 'RuneScape' },
    { id: 'elysian_spirit_shield', name: 'Elysian spirit shield', slot: 'weapon', price: 40, franchise: 'RuneScape' },
    { id: 'godsword', name: 'Godsword', slot: 'weapon', price: 30, franchise: 'RuneScape' },
    { id: 'granite_maul', name: 'Granite Maul', slot: 'weapon', price: 15, franchise: 'RuneScape' },
    { id: 'leaf_bladed_battleaxe', name: 'Leaf-Bladed Battleaxe', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'master_wand', name: 'Master Wand', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'rune_2h', name: 'Rune 2-Handed Sword', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'rune_crossbow', name: 'Rune Crossbow', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'rune_scimitar', name: 'Rune Scimitar', slot: 'weapon', price: 10, franchise: 'RuneScape' },
    { id: 'trident_of_the_seas', name: 'Trident of the Seas', slot: 'weapon', price: 25, franchise: 'RuneScape' },
    { id: 'tumekens_shadow', name: 'Tumeken\'s shadow', slot: 'weapon', price: 45, franchise: 'RuneScape' },
    { id: 'chillrend', name: 'Chillrend', slot: 'weapon', price: 35, franchise: 'Skyrim' },
    { id: 'dawnbreaker', name: 'Dawnbreaker', slot: 'weapon', price: 35, franchise: 'Skyrim' },
    { id: 'dawnguard_rune_axe', name: 'Dawnguard Rune Axe', slot: 'weapon', price: 25, franchise: 'Skyrim' },
    { id: 'mehrunes_razor', name: 'Mehrunes\' Razor', slot: 'weapon', price: 40, franchise: 'Skyrim' },
    { id: 'volendrung', name: 'Volendrung', slot: 'weapon', price: 40, franchise: 'Skyrim' },
    { id: 'wabbajack', name: 'Wabbajack', slot: 'weapon', price: 40, franchise: 'Skyrim' },
    { id: 'wuuthrad', name: 'Wuuthrad', slot: 'weapon', price: 35, franchise: 'Skyrim' },
    { id: 'last_prism', name: 'Last Prism', slot: 'weapon', price: 40, franchise: 'Terraria' },
    { id: 'meowmere', name: 'Meowmere', slot: 'weapon', price: 35, franchise: 'Terraria' },
    { id: 'rod_of_discord', name: 'Rod of Discord', slot: 'weapon', price: 40, franchise: 'Terraria' },
    { id: 'star_wrath', name: 'Star Wrath', slot: 'weapon', price: 35, franchise: 'Terraria' },
    { id: 'terra_blade', name: 'Terra Blade', slot: 'weapon', price: 35, franchise: 'Terraria' },
    { id: 'zenith', name: 'Zenith', slot: 'weapon', price: 45, franchise: 'Terraria' },
    { id: 'biggorons_sword', name: 'Biggoron\'s Sword', slot: 'weapon', price: 35, franchise: 'The Legend of Zelda' },
    { id: 'deku_shield', name: 'Deku Shield', slot: 'weapon', price: 10, franchise: 'The Legend of Zelda' },
    { id: 'hylian_shield', name: 'Hylian Shield', slot: 'weapon', price: 35, franchise: 'The Legend of Zelda' },
    { id: 'kokiri_sword', name: 'Kokiri Sword', slot: 'weapon', price: 15, franchise: 'The Legend of Zelda' },
    { id: 'master_sword', name: 'Master Sword', slot: 'weapon', price: 45, franchise: 'The Legend of Zelda' },
    { id: 'mirror_shield', name: 'Mirror Shield', slot: 'weapon', price: 30, franchise: 'The Legend of Zelda' },
    { id: 'aerondight', name: 'Aerondight', slot: 'weapon', price: 40, franchise: 'The Witcher' },
    { id: 'iris', name: 'Iris', slot: 'weapon', price: 40, franchise: 'The Witcher' },
    { id: 'arcanite_reaper', name: 'Arcanite Reaper', slot: 'weapon', price: 10, franchise: 'WoW' },
    { id: 'armageddon', name: 'Armageddon', slot: 'weapon', price: 20, franchise: 'WoW' },
    { id: 'ashbringer', name: 'Ashbringer', slot: 'weapon', price: 50, franchise: 'WoW' },
    { id: 'atiesh', name: 'Atiesh, Greatstaff of the Guardian', slot: 'weapon', price: 40, short: 'Atiesh', franchise: 'WoW' },
    { id: 'bonebiter', name: 'Bonebiter', slot: 'weapon', price: 10, franchise: 'WoW' },
    { id: 'bonereaver', name: 'Bonereaver\'s Edge', slot: 'weapon', price: 25, short: 'Bonereaver', franchise: 'WoW' },
    { id: 'bulwark_of_azzinoth', name: 'Bulwark of Azzinoth', slot: 'weapon', price: 35, franchise: 'WoW' },
    { id: 'dal_rends', name: 'Dal\'Rend\'s Sacred Charge', slot: 'weapon', price: 10, franchise: 'WoW' },
    { id: 'doomhammer', name: 'Doomhammer', slot: 'weapon', price: 40, franchise: 'WoW' },
    { id: 'dragonwrath', name: 'Dragonwrath, Tarecgosa\'s Rest', slot: 'weapon', price: 45, franchise: 'WoW' },
    { id: 'fists_of_fury', name: 'Fists of Fury', slot: 'weapon', price: 20, franchise: 'WoW' },
    { id: 'mourne_frost', name: 'Frostmourne', slot: 'weapon', price: 50, short: 'Frostmourne', franchise: 'WoW' },
    { id: 'gorehowl', name: 'Gorehowl', slot: 'weapon', price: 25, franchise: 'WoW' },
    { id: 'lok_delar', name: 'Lok\'delar, Stave of the Ancient Keepers', slot: 'weapon', price: 20, short: 'Lok\'delar', franchise: 'WoW' },
    { id: 'nerfing_crossbow', name: 'Nerfing Crossbow', slot: 'weapon', price: 10, franchise: 'WoW' },
    { id: 'mourne', name: 'Shadowmourne', slot: 'weapon', price: 45, franchise: 'WoW' },
    { id: 'skull_of_guldan', name: 'Skull of Gul\'dan', slot: 'weapon', price: 30, franchise: 'WoW' },
    { id: 'skullflame_shield', name: 'Skullflame Shield', slot: 'weapon', price: 25, franchise: 'WoW' },
    { id: 'spinal_reaper', name: 'Spinal Reaper', slot: 'weapon', price: 20, franchise: 'WoW' },
    { id: 'staff_of_dominance', name: 'Staff of Dominance', slot: 'weapon', price: 20, franchise: 'WoW' },
    { id: 'staff_of_the_archmage', name: 'Staff of the Archmage', slot: 'weapon', price: 20, franchise: 'WoW' },
    { id: 'staff_of_the_immortal', name: 'Staff of the Immortal', slot: 'weapon', price: 25, franchise: 'WoW' },
    { id: 'staff_of_the_shadow_flame', name: 'Staff of the Shadow Flame', slot: 'weapon', price: 25, franchise: 'WoW' },
    { id: 'sulfuras', name: 'Sulfuras, Hand of Ragnaros', slot: 'weapon', price: 50, franchise: 'WoW' },
    { id: 'the_burning_war_glaive', name: 'The Burning War-Glaive', slot: 'weapon', price: 15, franchise: 'WoW' },
    { id: 'thoridal_fury_of_the_stars', name: 'Thori\'dal, the Stars\' Fury', slot: 'weapon', price: 45, franchise: 'WoW' },
    { id: 'thunderfury', name: 'Thunderfury, Blessed Blade of the Windseeker', slot: 'weapon', price: 50, short: 'Thunderfury', franchise: 'WoW' },
    { id: 'verigans_fist', name: 'Verigan\'s Fist', slot: 'weapon', price: 10, franchise: 'WoW' },
    { id: 'warglaives', name: 'Warglaives of Azzinoth', slot: 'weapon', price: 45, short: 'Warglaives', franchise: 'WoW' },
    { id: 'whirlwind_axe', name: 'Whirlwind Axe', slot: 'weapon', price: 10, franchise: 'WoW' },
    { id: 'zin_rokh', name: 'Zin\'rokh, Destroyer of Worlds', slot: 'weapon', price: 25, short: 'Zin\'rokh', franchise: 'WoW' },

    // Gloves
    { id: 'gauntlets_of_hill_giant_strength', name: 'Gauntlets of Hill Giant Strength', slot: 'gloves', price: 40, franchise: 'Baldur\'s Gate' },
    { id: 'black_knight_gauntlets', name: 'Black Knight Gauntlets', slot: 'gloves', price: 35, franchise: 'Dark Souls' },
    { id: 'havels_gauntlets', name: 'Havel\'s Gauntlets', slot: 'gloves', price: 50, franchise: 'Dark Souls' },
    { id: 'raging_wolf_gauntlets', name: 'Raging Wolf Gauntlets', slot: 'gloves', price: 25, franchise: 'Elden Ring' },
    { id: 'diamond_gloves', name: 'Diamond Gloves', slot: 'gloves', price: 15, franchise: 'Final Fantasy' },
    { id: 'genji_gauntlet', name: 'Genji Gauntlet', slot: 'gloves', price: 25, franchise: 'Final Fantasy' },
    { id: 'genji_gloves', name: 'Genji Gloves', slot: 'gloves', price: 10, franchise: 'Final Fantasy' },
    { id: 'power_gauntlet', name: 'Power Gauntlet', slot: 'gloves', price: 15, franchise: 'Final Fantasy' },
    { id: 'assassin_gloves', name: 'Assassin Gloves', slot: 'gloves', price: 15, franchise: 'Guild Wars' },
    { id: 'gladiator_gauntlets', name: 'Gladiator Gauntlets', slot: 'gloves', price: 10, franchise: 'Guild Wars' },
    { id: 'obsidian_gauntlets', name: 'Obsidian Gauntlets', slot: 'gloves', price: 30, franchise: 'Guild Wars' },
    { id: 'dragon_hide_gloves', name: 'Dragon-Hide Gloves', slot: 'gloves', price: 15, franchise: 'Harry Potter' },
    { id: 'gauntlet_of_sauron', name: 'Gauntlet of Sauron', slot: 'gloves', price: 50, franchise: 'Lord of the Rings' },
    { id: 'barrows_gloves', name: 'Barrows Gloves', slot: 'gloves', price: 25, franchise: 'RuneScape' },
    { id: 'combat_bracelet', name: 'Combat Bracelet', slot: 'gloves', price: 10, franchise: 'RuneScape' },
    { id: 'dragon_gloves', name: 'Dragon Gloves', slot: 'gloves', price: 10, franchise: 'RuneScape' },
    { id: 'ferocious_gloves', name: 'Ferocious Gloves', slot: 'gloves', price: 30, franchise: 'RuneScape' },
    { id: 'rune_gloves', name: 'Rune Gloves', slot: 'gloves', price: 10, franchise: 'RuneScape' },
    { id: 'torva_gloves', name: 'Torva Gloves', slot: 'gloves', price: 50, franchise: 'RuneScape' },
    { id: 'daedric_gauntlets', name: 'Daedric Gauntlets', slot: 'gloves', price: 40, franchise: 'Skyrim' },
    { id: 'gloves_of_the_pugilist', name: 'Gloves of the Pugilist', slot: 'gloves', price: 25, franchise: 'Skyrim' },
    { id: 'feral_claws', name: 'Feral Claws', slot: 'gloves', price: 15, franchise: 'Terraria' },
    { id: 'fire_gauntlet', name: 'Fire Gauntlet', slot: 'gloves', price: 35, franchise: 'Terraria' },
    { id: 'mechanical_glove', name: 'Mechanical Glove', slot: 'gloves', price: 30, franchise: 'Terraria' },
    { id: 'golden_gauntlets', name: 'Golden Gauntlets', slot: 'gloves', price: 50, franchise: 'The Legend of Zelda' },
    { id: 'silver_gauntlets', name: 'Silver Gauntlets', slot: 'gloves', price: 25, franchise: 'The Legend of Zelda' },
    { id: 'grandmaster_wolven_gauntlets', name: 'Grandmaster Wolven Gauntlets', slot: 'gloves', price: 50, franchise: 'The Witcher' },
    { id: 'griffin_gauntlets', name: 'Griffin Gauntlets', slot: 'gloves', price: 25, franchise: 'The Witcher' },
    { id: 'arcanist_gloves', name: 'Arcanist Gloves', slot: 'gloves', price: 15, franchise: 'WoW' },
    { id: 'bloodfang_gloves', name: 'Bloodfang Gloves', slot: 'gloves', price: 20, franchise: 'WoW' },
    { id: 'dragonstalker_gauntlets', name: 'Dragonstalker Gauntlets', slot: 'gloves', price: 20, franchise: 'WoW' },
    { id: 'felheart_gloves', name: 'Felheart Gloves', slot: 'gloves', price: 15, franchise: 'WoW' },
    { id: 'gauntlets_of_might', name: 'Gauntlets of Might', slot: 'gloves', price: 15, franchise: 'WoW' },
    { id: 'gauntlets_of_ten_storms', name: 'Gauntlets of Ten Storms', slot: 'gloves', price: 35, franchise: 'WoW' },
    { id: 'handguards_of_transcendence', name: 'Handguards of Transcendence', slot: 'gloves', price: 20, franchise: 'WoW' },
    { id: 'judgement_gloves', name: 'Judgement Gloves', slot: 'gloves', price: 20, franchise: 'WoW' },

    // Cape
    { id: 'cloak_of_displacement', name: 'Cloak of Displacement', slot: 'cape', price: 35, franchise: 'Baldur\'s Gate' },
    { id: 'cloak_of_protection', name: 'Cloak of Protection', slot: 'cape', price: 25, franchise: 'Baldur\'s Gate' },
    { id: 'black_cape', name: 'Black Cape', slot: 'cape', price: 10, franchise: 'Final Fantasy' },
    { id: 'cape_of_defense', name: 'Cape of Defense', slot: 'cape', price: 15, franchise: 'Final Fantasy' },
    { id: 'ascalon_cape', name: 'Ascalon Cape', slot: 'cape', price: 15, franchise: 'Guild Wars' },
    { id: 'cloak_of_invisibility', name: 'Cloak of Invisibility', slot: 'cape', price: 40, franchise: 'Harry Potter' },
    { id: 'gryffindor_scarf', name: 'Gryffindor Scarf', slot: 'cape', price: 10, franchise: 'Harry Potter' },
    { id: 'cloak_of_lorien', name: 'Cloak of Lórien', slot: 'cape', price: 30, franchise: 'Lord of the Rings' },
    { id: 'ardy_cape', name: 'Ardougne Cloak', slot: 'cape', price: 15, franchise: 'RuneScape' },
    { id: 'avas_accumulator', name: 'Ava\'s Accumulator', slot: 'cape', price: 25, franchise: 'RuneScape' },
    { id: 'legendary_cape', name: 'Cape of Legends', slot: 'cape', price: 15, franchise: 'RuneScape' },
    { id: 'fire_cape', name: 'Fire Cape', slot: 'cape', price: 25, franchise: 'RuneScape' },
    { id: 'infernal_cape', name: 'Infernal Cape', slot: 'cape', price: 40, franchise: 'RuneScape' },
    { id: 'max_cape', name: 'Max Cape', slot: 'cape', price: 50, franchise: 'RuneScape' },
    { id: 'obsidian_cape', name: 'Obsidian Cape', slot: 'cape', price: 10, franchise: 'RuneScape' },
    { id: 'team_cape', name: 'Team Cape', slot: 'cape', price: 10, franchise: 'RuneScape' },
    { id: 'angel_wings', name: 'Angel Wings', slot: 'cape', price: 25, franchise: 'Terraria' },
    { id: 'solar_wings', name: 'Solar Wings', slot: 'cape', price: 50, franchise: 'Terraria' },
    { id: 'paraglider', name: 'Paraglider', slot: 'cape', price: 25, franchise: 'The Legend of Zelda' },
    { id: 'ashjrakamas_shroud', name: 'Ashjra\'kamas, Shroud of Resolve', slot: 'cape', price: 40, franchise: 'WoW' },
    { id: 'drape_of_the_untamed_predator', name: 'Drape of the Untamed Predator', slot: 'cape', price: 15, franchise: 'WoW' },
    { id: 'netherwind_cape', name: 'Netherwind Cape', slot: 'cape', price: 20, franchise: 'WoW' },
    { id: 'qian_ying', name: 'Qian-Ying, Fortitude of Niuzao', slot: 'cape', price: 50, franchise: 'WoW' },
    { id: 'shadowcraft_cape', name: 'Shadowcraft Cape', slot: 'cape', price: 15, franchise: 'WoW' },
    { id: 'travelers_cloak', name: 'Traveler\'s Cloak', slot: 'cape', price: 10, franchise: 'Generic' },

    // Boots
    { id: 'boots_of_speed', name: 'Boots of Speed', slot: 'boots', price: 35, franchise: 'Baldur\'s Gate' },
    { id: 'diamond_shoes', name: 'Diamond Shoes', slot: 'boots', price: 15, franchise: 'Final Fantasy' },
    { id: 'genji_boots', name: 'Genji Boots', slot: 'boots', price: 25, franchise: 'Final Fantasy' },
    { id: 'hermes_sandals', name: 'Hermes Sandals', slot: 'boots', price: 15, franchise: 'Final Fantasy' },
    { id: 'winged_boots', name: 'Winged Shoes', slot: 'boots', price: 20, franchise: 'Final Fantasy' },
    { id: 'assassin_boots', name: 'Assassin Boots', slot: 'boots', price: 15, franchise: 'Guild Wars' },
    { id: 'gladiator_boots', name: 'Gladiator Boots', slot: 'boots', price: 10, franchise: 'Guild Wars' },
    { id: 'obsidian_boots', name: 'Obsidian Boots', slot: 'boots', price: 30, franchise: 'Guild Wars' },
    { id: 'diamond_boots', name: 'Diamond Boots', slot: 'boots', price: 20, franchise: 'Minecraft' },
    { id: 'netherite_boots', name: 'Netherite Boots', slot: 'boots', price: 35, franchise: 'Minecraft' },
    { id: 'dragon_boots', name: 'Dragon Boots', slot: 'boots', price: 10, franchise: 'RuneScape' },
    { id: 'guardian_boots', name: 'Guardian Boots', slot: 'boots', price: 25, franchise: 'RuneScape' },
    { id: 'infinity_boots', name: 'Infinity Boots', slot: 'boots', price: 20, franchise: 'RuneScape' },
    { id: 'pegasian_boots', name: 'Pegasian Boots', slot: 'boots', price: 30, franchise: 'RuneScape' },
    { id: 'primordial_boots', name: 'Primordial Boots', slot: 'boots', price: 30, franchise: 'RuneScape' },
    { id: 'rune_boots', name: 'Rune Boots', slot: 'boots', price: 10, franchise: 'RuneScape' },
    { id: 'daedric_boots', name: 'Daedric Boots', slot: 'boots', price: 40, franchise: 'Skyrim' },
    { id: 'ebony_boots', name: 'Ebony Boots', slot: 'boots', price: 35, franchise: 'Skyrim' },
    { id: 'hermes_boots', name: 'Hermes Boots', slot: 'boots', price: 15, franchise: 'Terraria' },
    { id: 'lightning_boots', name: 'Lightning Boots', slot: 'boots', price: 35, franchise: 'Terraria' },
    { id: 'terraspark_boots', name: 'Terraspark Boots', slot: 'boots', price: 50, franchise: 'Terraria' },
    { id: 'hover_boots', name: 'Hover Boots', slot: 'boots', price: 25, franchise: 'The Legend of Zelda' },
    { id: 'iron_boots', name: 'Iron Boots', slot: 'boots', price: 15, franchise: 'The Legend of Zelda' },
    { id: 'pegasus_boots', name: 'Pegasus Boots', slot: 'boots', price: 50, franchise: 'The Legend of Zelda' },
    { id: 'feline_boots', name: 'Feline Boots', slot: 'boots', price: 25, franchise: 'The Witcher' },
    { id: 'grandmaster_wolven_boots', name: 'Grandmaster Wolven Boots', slot: 'boots', price: 50, franchise: 'The Witcher' },
    { id: 'bloodfang_boots', name: 'Bloodfang Boots', slot: 'boots', price: 20, franchise: 'WoW' },
    { id: 'boots_quelthalas', name: 'Boots of Quel\'thalas', slot: 'boots', price: 20, franchise: 'WoW' },
    { id: 'chromatic_boots', name: 'Chromatic Boots', slot: 'boots', price: 20, franchise: 'WoW' },
    { id: 'inferno_tempered_boots', name: 'Inferno Tempered Boots', slot: 'boots', price: 25, franchise: 'WoW' },
    { id: 'judgement_boots', name: 'Judgement Boots', slot: 'boots', price: 20, franchise: 'WoW' },
    { id: 'swift_boots', name: 'Swift Boots', slot: 'boots', price: 10, franchise: 'WoW' },
];

const TITLES = [
    { id: 'crystal_champion', name: 'Champion of the Crystals', price: 10, franchise: 'Final Fantasy' },
    { id: 'crystal_bearer', name: 'Crystal Bearer', price: 10, franchise: 'Final Fantasy' },
    { id: 'hero_of_light', name: 'Hero of Light', price: 10, franchise: 'Final Fantasy' },
    { id: 'knight_of_the_round', name: 'Knight of the Round', price: 10, franchise: 'Final Fantasy' },
    { id: 'master_of_summoning', name: 'Master Summoner', price: 10, franchise: 'Final Fantasy' },
    { id: 'warrior_of_light', name: 'Warrior of Light', price: 10, franchise: 'Final Fantasy' },
    { id: 'wielder_of_excalibur', name: 'Wielder of Excalibur', price: 10, franchise: 'Final Fantasy' },
    { id: 'champion_of_ascalon', name: 'Champion of Ascalon', price: 10, franchise: 'Guild Wars' },
    { id: 'guardian_of_the_north', name: 'Guardian of the North', price: 10, franchise: 'Guild Wars' },
    { id: 'hero_of_ascalon', name: 'Hero of Ascalon', price: 10, franchise: 'Guild Wars' },
    { id: 'legendary_defender', name: 'Legendary Defender', price: 10, franchise: 'Guild Wars' },
    { id: 'protector_of_elona', name: 'Protector of Elona', price: 10, franchise: 'Guild Wars' },
    { id: 'vanquisher', name: 'Vanquisher', price: 10, franchise: 'Guild Wars' },
    { id: 'barrows_champion', name: 'Barrows Champion', price: 10, franchise: 'RuneScape' },
    { id: 'champion_of_gielinor', name: 'Champion of Gielinor', price: 10, franchise: 'RuneScape' },
    { id: 'demon_slayer', name: 'Demon Slayer', price: 10, franchise: 'RuneScape' },
    { id: 'dragonslayer', name: 'Dragonslayer', price: 10, franchise: 'RuneScape' },
    { id: 'fire_capist', name: 'Fire Cape Champion', price: 10, franchise: 'RuneScape' },
    { id: 'master_slayer', name: 'Master Slayer', price: 10, franchise: 'RuneScape' },
    { id: 'scion_of_zamorak', name: 'Scion of Zamorak', price: 10, franchise: 'RuneScape' },
    { id: 'servant_of_saradomin', name: 'Servant of Saradomin', price: 10, franchise: 'RuneScape' },
    { id: 'bane_of_the_fallen_king', name: 'Bane of the Fallen King', price: 10, franchise: 'WoW' },
    { id: 'champion_of_the_frozen_wastes', name: 'Champion of the Frozen Wastes', price: 10, franchise: 'WoW' },
    { id: 'champion_of_the_naaru', name: 'Champion of the Naaru', price: 10, franchise: 'WoW' },
    { id: 'conqueror_of_naxxramas', name: 'Conqueror of Naxxramas', price: 10, franchise: 'WoW' },
    { id: 'hand_of_a_dal', name: 'Hand of A\'dal', price: 10, franchise: 'WoW' },
    { id: 'keeper_of_the_flame', name: 'Keeper of the Flame', price: 10, franchise: 'WoW' },
    { id: 'of_the_nightfall', name: 'of the Nightfall', price: 10, franchise: 'WoW' },
    { id: 'slayer_of_arthas', name: 'Slayer of Arthas', price: 10, franchise: 'WoW' },
    { id: 'the_exalted', name: 'The Exalted', price: 10, franchise: 'WoW' },
    { id: 'the_explorer', name: 'The Explorer', price: 10, franchise: 'WoW' },
    { id: 'the_undying_flame', name: 'The Flamebreaker', price: 10, franchise: 'WoW' },
    { id: 'the_immortal', name: 'The Immortal', price: 10, franchise: 'WoW' },
    { id: 'the_insane', name: 'The Insane', price: 10, franchise: 'WoW' },
    { id: 'the_patient', name: 'The Patient', price: 10, franchise: 'WoW' },
    { id: 'the_undying', name: 'The Undying', price: 10, franchise: 'WoW' },
    { id: 'bane_of_demons', name: 'Bane of Demons', price: 10, franchise: 'Generic' },
    { id: 'demonbane', name: 'Demonbane', price: 10, franchise: 'Generic' },
    { id: 'hero_of_the_realm', name: 'Hero of the Realm', price: 10, franchise: 'Generic' },
    { id: 'lord_of_war', name: 'Lord of War', price: 10, franchise: 'Generic' },
    { id: 'shadowhunter', name: 'Shadowhunter', price: 10, franchise: 'Generic' },
    { id: 'the_chosen', name: 'The Chosen', price: 10, franchise: 'Generic' },
    { id: 'the_legend', name: 'The Legend', price: 10, franchise: 'Generic' },
    { id: 'warden_of_the_realm', name: 'Warden of the Realm', price: 10, franchise: 'Generic' },
];

const CLASSES = [
    { id: 'bard', name: 'Bard', price: 10, franchise: 'Final Fantasy' },
    { id: 'black_mage', name: 'Black Mage', price: 10, franchise: 'Final Fantasy' },
    { id: 'dark_knight', name: 'Dark Knight', price: 10, franchise: 'Final Fantasy' },
    { id: 'dragoon', name: 'Dragoon', price: 10, franchise: 'Final Fantasy' },
    { id: 'machinist', name: 'Machinist', price: 10, franchise: 'Final Fantasy' },
    { id: 'ninja', name: 'Ninja', price: 10, franchise: 'Final Fantasy' },
    { id: 'red_mage', name: 'Red Mage', price: 10, franchise: 'Final Fantasy' },
    { id: 'samurai', name: 'Samurai', price: 10, franchise: 'Final Fantasy' },
    { id: 'summoner', name: 'Summoner', price: 10, franchise: 'Final Fantasy' },
    { id: 'white_mage', name: 'White Mage', price: 10, franchise: 'Final Fantasy' },
    { id: 'assassin', name: 'Assassin', price: 10, franchise: 'Guild Wars' },
    { id: 'elementalist', name: 'Elementalist', price: 10, franchise: 'Guild Wars' },
    { id: 'mesmer', name: 'Mesmer', price: 10, franchise: 'Guild Wars' },
    { id: 'necromancer', name: 'Necromancer', price: 10, franchise: 'Guild Wars' },
    { id: 'paragon', name: 'Paragon', price: 10, franchise: 'Guild Wars' },
    { id: 'ritualist', name: 'Ritualist', price: 10, franchise: 'Guild Wars' },
    { id: 'death_knight', name: 'Death Knight', price: 10, franchise: 'WoW' },
    { id: 'demon_hunter', name: 'Demon Hunter', price: 10, franchise: 'WoW' },
    { id: 'druid', name: 'Druid', price: 10, franchise: 'WoW' },
    { id: 'hunter', name: 'Hunter', price: 10, franchise: 'WoW' },
    { id: 'mage', name: 'Mage', price: 10, franchise: 'WoW' },
    { id: 'paladin', name: 'Paladin', price: 10, franchise: 'WoW' },
    { id: 'priest', name: 'Priest', price: 10, franchise: 'WoW' },
    { id: 'rogue', name: 'Rogue', price: 10, franchise: 'WoW' },
    { id: 'shaman', name: 'Shaman', price: 10, franchise: 'WoW' },
    { id: 'warlock', name: 'Warlock', price: 10, franchise: 'WoW' },
    { id: 'warrior', name: 'Warrior', price: 10, franchise: 'WoW' },
    { id: 'alchemist', name: 'Alchemist', price: 10, franchise: 'Generic' },
    { id: 'battle_mage', name: 'Battlemage', price: 10, franchise: 'Generic' },
    { id: 'berserker', name: 'Berserker', price: 10, franchise: 'Generic' },
    { id: 'monk', name: 'Monk', price: 10, franchise: 'Generic' },
    { id: 'ranger', name: 'Ranger', price: 10, franchise: 'Generic' },
    { id: 'spellblade', name: 'Spellblade', price: 10, franchise: 'Generic' },
];

const RACES = [
    { id: 'lalafell', name: 'Lalafell', price: 10, franchise: 'Final Fantasy' },
    { id: 'miqote', name: 'Miqo\'te', price: 10, franchise: 'Final Fantasy' },
    { id: 'moogle', name: 'Moogle', price: 10, franchise: 'Final Fantasy' },
    { id: 'roegadyn', name: 'Roegadyn', price: 10, franchise: 'Final Fantasy' },
    { id: 'viera', name: 'Viera', price: 10, franchise: 'Final Fantasy' },
    { id: 'asura', name: 'Asura', price: 10, franchise: 'Guild Wars' },
    { id: 'charr', name: 'Charr', price: 10, franchise: 'Guild Wars' },
    { id: 'sylvari', name: 'Sylvari', price: 10, franchise: 'Guild Wars' },
    { id: 'blood_elf', name: 'Blood Elf', price: 10, franchise: 'WoW' },
    { id: 'draenei', name: 'Draenei', price: 10, franchise: 'WoW' },
    { id: 'forsaken', name: 'Forsaken', price: 10, franchise: 'WoW' },
    { id: 'goblin', name: 'Goblin', price: 10, franchise: 'WoW' },
    { id: 'night_elf', name: 'Night Elf', price: 10, franchise: 'WoW' },
    { id: 'tauren', name: 'Tauren', price: 10, franchise: 'WoW' },
    { id: 'troll', name: 'Troll', price: 10, franchise: 'WoW' },
    { id: 'worgen', name: 'Worgen', price: 10, franchise: 'WoW' },
    { id: 'dragonborn', name: 'Dragonborn', price: 10, franchise: 'Generic' },
    { id: 'dwarf', name: 'Dwarf', price: 10, franchise: 'Generic' },
    { id: 'elf', name: 'Elf', price: 10, franchise: 'Generic' },
    { id: 'gnome', name: 'Gnome', price: 10, franchise: 'Generic' },
    { id: 'halfling', name: 'Halfling', price: 10, franchise: 'Generic' },
    { id: 'human', name: 'Human', price: 10, franchise: 'Generic' },
    { id: 'orc', name: 'Orc', price: 10, franchise: 'Generic' },
    { id: 'tiefling', name: 'Tiefling', price: 10, franchise: 'Generic' },
];

const ALL = [...GEAR, ...TITLES, ...CLASSES, ...RACES];

const findEntry = (id) => ALL.find((entry) => entry.id === id) || null;

/* Rarity label for gear, from its price alone (so it can't drift from the
 * price). Common 10, uncommon 15-20, rare 25-30, epic 35-45, legendary 50.
 */
const RARITIES = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary'];
const rarityFor = (price) => {
    if (price >= 50) return 'Legendary';
    if (price >= 35) return 'Epic';
    if (price >= 25) return 'Rare';
    if (price >= 15) return 'Uncommon';
    return 'Common';
};

module.exports = { GEAR_SLOTS, DEFAULT_CLASS, GEAR, TITLES, CLASSES, RACES, ALL, findEntry, rarityFor, RARITIES };
